---
title: Sleep Er.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
paginate: 5
paginate_path: "/blog/page:num"
permalink: "/blog/:year/:title/"
markdown: kramdown
highlighter: rouge
excerpt_separator: "<!-- more -->"
name: David Makin
description: Personal blog about various tech.  PHP, bash, Linux related.
url: https://sleep-er.co.uk
